notifications:
  email: false

language: php

php:
  - '7.1'
  - '7.2'

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - make

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'